/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsWorkshopsRouteImport } from './routes/news.workshops'
import { Route as NewsTrainingRouteImport } from './routes/news.training'
import { Route as NewsStoriesRouteImport } from './routes/news.stories'
import { Route as NewsConferencesRouteImport } from './routes/news.conferences'
import { Route as NewsAnnouncementsRouteImport } from './routes/news.announcements'
import { Route as AlbumAlbumIdRouteImport } from './routes/album.$albumId'

const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsWorkshopsRoute = NewsWorkshopsRouteImport.update({
  id: '/news/workshops',
  path: '/news/workshops',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsTrainingRoute = NewsTrainingRouteImport.update({
  id: '/news/training',
  path: '/news/training',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsStoriesRoute = NewsStoriesRouteImport.update({
  id: '/news/stories',
  path: '/news/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsConferencesRoute = NewsConferencesRouteImport.update({
  id: '/news/conferences',
  path: '/news/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsAnnouncementsRoute = NewsAnnouncementsRouteImport.update({
  id: '/news/announcements',
  path: '/news/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/goals': typeof GoalsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/conferences': typeof NewsConferencesRoute
  '/news/stories': typeof NewsStoriesRoute
  '/news/training': typeof NewsTrainingRoute
  '/news/workshops': typeof NewsWorkshopsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/goals': typeof GoalsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/conferences': typeof NewsConferencesRoute
  '/news/stories': typeof NewsStoriesRoute
  '/news/training': typeof NewsTrainingRoute
  '/news/workshops': typeof NewsWorkshopsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/goals': typeof GoalsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/news/announcements': typeof NewsAnnouncementsRoute
  '/news/conferences': typeof NewsConferencesRoute
  '/news/stories': typeof NewsStoriesRoute
  '/news/training': typeof NewsTrainingRoute
  '/news/workshops': typeof NewsWorkshopsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/donate'
    | '/goals'
    | '/album/$albumId'
    | '/news/announcements'
    | '/news/conferences'
    | '/news/stories'
    | '/news/training'
    | '/news/workshops'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/donate'
    | '/goals'
    | '/album/$albumId'
    | '/news/announcements'
    | '/news/conferences'
    | '/news/stories'
    | '/news/training'
    | '/news/workshops'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/contact'
    | '/donate'
    | '/goals'
    | '/album/$albumId'
    | '/news/announcements'
    | '/news/conferences'
    | '/news/stories'
    | '/news/training'
    | '/news/workshops'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GoalsRoute: typeof GoalsRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  NewsAnnouncementsRoute: typeof NewsAnnouncementsRoute
  NewsConferencesRoute: typeof NewsConferencesRoute
  NewsStoriesRoute: typeof NewsStoriesRoute
  NewsTrainingRoute: typeof NewsTrainingRoute
  NewsWorkshopsRoute: typeof NewsWorkshopsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/workshops': {
      id: '/news/workshops'
      path: '/news/workshops'
      fullPath: '/news/workshops'
      preLoaderRoute: typeof NewsWorkshopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/training': {
      id: '/news/training'
      path: '/news/training'
      fullPath: '/news/training'
      preLoaderRoute: typeof NewsTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/stories': {
      id: '/news/stories'
      path: '/news/stories'
      fullPath: '/news/stories'
      preLoaderRoute: typeof NewsStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/conferences': {
      id: '/news/conferences'
      path: '/news/conferences'
      fullPath: '/news/conferences'
      preLoaderRoute: typeof NewsConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/announcements': {
      id: '/news/announcements'
      path: '/news/announcements'
      fullPath: '/news/announcements'
      preLoaderRoute: typeof NewsAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GoalsRoute: GoalsRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  NewsAnnouncementsRoute: NewsAnnouncementsRoute,
  NewsConferencesRoute: NewsConferencesRoute,
  NewsStoriesRoute: NewsStoriesRoute,
  NewsTrainingRoute: NewsTrainingRoute,
  NewsWorkshopsRoute: NewsWorkshopsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
